"Boot with standard options"  "root=ZFS=zroot/arch0/root zswap.enabled=0 rw spl.spl_hostid=0x00bab10c"
"Boot to single-user mode"    "root=ZFS=zroot/arch0/root zswap.enabled=0 rw spl.spl_hostid=0x00bab10c single"
"Boot with minimal options"   "ro root="
