hostonly="yes"
hostonly_cmdline="no"
fscks="no"
early_microcode="yes"
# ZFS datasets are already compressed, use uncompressed initramfs to avoid double compression
compress="cat"
omit_dracutmodules+=" network btrfs brltty "
